### ISSUE TITLE
Video gets disappeared on hitting escape key

### ISSUE THREAD

**Issue by balacsm** [topcoder-platform/Training-Challenges#101]
Steps to Reproduce:

1. Navigate to https://www.topcoder.com/
2. click over the home page video
3. Press Esc button

Actual Result:
Video gets disappeared and it never displayed for the user to play the video again

Expected Result: 
Video thumbnail/play button should appear again for the user to play again

Screenshots or screencast URL:
![image](https://user-images.githubusercontent.com/63979134/79699498-dd1bbd80-8287-11ea-91f8-c2bc268d228f.png)

Device/OS/Browser Information:
Windows 10 Pro
chrome: Version 81.0.4044.113 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Great catch @balacsm !!
