### ISSUE TITLE
[maintenance] no one is solving / closing the issues

### ISSUE THREAD

**Issue by geyuqiu** [topcoder-platform/Training-Challenges#104]
![Bildschirmfoto 2020-04-25 um 11 01 59](https://user-images.githubusercontent.com/4540661/80275845-6138cf80-86e4-11ea-813c-17cd25950333.png)

this percentage is not acceptable for a github repo
101/ 103

**Comment by nithyaasworld** [comment]
Hey @geyuqiu The issues in this repo will not be closed. We review the issues and classify it using one of the followings labels: Accepted, Not-Accepted, Duplicate. 

This way, the new bug hunters can see the old bugs and will not duplicate the issue.

Please feel free to reach out to us in the forum, if you have any questions. Thanks!
