### ISSUE TITLE
[UX / Usability] register button for a challenge can be pushed several times

### ISSUE THREAD

**Issue by geyuqiu** [topcoder-platform/Training-Challenges#106]
Steps to Reproduce:

* precondition: complete nda etc.
* open a challenge
* register for it
* and wait for it...

Actual Result:

* can push register button several times. 
* user is confused
* sometimes, an error is displayed: cannot not register anymore ...
* `unregister` is visible after 3-5 seconds normally

Expected Result: 

register button is not accessible after first click on it

* spinning, e.g. `LOADING`
* button register changes to unregister with different color 

Device/OS/Browser Information:
MacOs, Chrome

**Comment by nithyaasworld** [comment]
Good job @geyuqiu 

Always attach a proof to the bug in means of screenshot or a video to add more value to your bug. Some times, the bug cannot always be reproducible for everyone. So a proof will help the reviewer/developer to understand more about the bug.
