### ISSUE TITLE
No hand cursor while hovering over the notification icon in Challenges page

### ISSUE THREAD

**Issue by naveejka** [topcoder-platform/Training-Challenges#109]
**Bug Title:** No hand cursor while hovering over the notification icon in Challenges page

**Steps to Reproduce:**
1. Open any challenge, after logging in. For eg:- https://www.topcoder.com/challenges/30108180
2. Point your mouse on the notification icon on the top right side of the page, near your topcoder handle. 

**Actual Result:**
Mouse pointer remain as it is.  but changes to hand image, when the mouse is placed on other icons and clickable links.  This issues is however not there in another page ([Topcoder Projects](https://connect.topcoder.com/projects)) for the same notification icon

**Expected Result:** 
Hand image icon while hovering over the Notification Icon.

**Screenshots or screencast URL:**
Screenshot from Challenges page where hover icon is not visible
![Screenshot from Challenges page where hover icon is not visible](https://user-images.githubusercontent.com/31006526/80470198-4a51e180-895f-11ea-9e79-058219ed8d82.png)

Screenshot from topcoder project where hovering works
![Screenshot from topcoder project where hovering works](https://user-images.githubusercontent.com/31006526/80470225-52aa1c80-895f-11ea-8974-0fabd2a2b236.png)

**Device/OS/Browser Information:**
Chrome on Windows 10 Desktop

**Comment by nithyaasworld** [comment]
Great work @naveejka !!
