### ISSUE TITLE
Profile Picture not displayed   

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/Training-Challenges#11]
1. Go to : "Challenge Forum"  the profile picture of the topcoder member does not reflect.
**ACTUAL RESULT:**  The profile picture is not displayed.

**EXPECTED RESULT:** The profile picture of the member should be visible once in the challenge forum.
CHECK THE ZIP FILE BELOW:

Device/OS/Browser Information: Linux,Ubuntu
OS: Kali
Browser information:CHromium Browser Version 73.0.3683.75 (Developer Build) built on Debian buster/side, running on Debian kali-rolling (32-bit)
[profile.zip](https://github.com/topcoder-platform/Training-Challenges/files/3898650/profile.zip)
![profile](https://user-images.githubusercontent.com/37167721/69756961-c1930780-116c-11ea-9178-0f9f4866b452.jpg)

**Comment by nithyaasworld** [comment]
It first comes under Functional bug, so this can be classified as Functional bug than UX.

**Comment by Rokit12** [comment]
Thnak you for the invitation
