### ISSUE TITLE
[Function Bug] Wrong email format is getting accepted

### ISSUE THREAD

**Issue by pranishi** [topcoder-platform/Training-Challenges#111]
**Steps to Reproduce:**
1. Click on "http://www.topcoder.com" link
2. Navigate to "Community" tab from the header
2. Click on Support icon at the footer
3. Enter the email format "abc@yy.com.com.com"/"abc@123.com"
**Expected Result:** This email format should not be accepted. There should be a single dot and an appropriate domain name
**Observed Result:** Wrong Email formats are getting accepted
**Browser info:** Google chrome (Version 81.0.4044.122 (Official Build) (64-bit))
**GIF**
![email](https://user-images.githubusercontent.com/64552582/80634082-7b91e680-8a1f-11ea-8c1a-9fae70719bc6.gif)

**Comment by nithyaasworld** [comment]
@pranishi Not really a bug. Email Validation still happens following a set of standards.

If you still find that, it violates the information stated here https://deliverbility.com/valid-email-address-format/ or any other information about email-format, please reply with more details.
