### ISSUE TITLE
[UI Bug]: Overlapping of box with the Filter box

### ISSUE THREAD

**Issue by pranishi** [topcoder-platform/Training-Challenges#112]
**Steps to Reproduce:**
1. Click on the link "http://www.topcoder.com"
2. Navigate to "https://www.topcoder.com/blog/"
3. Type few characters in the Search box lets say "test"
4. Click on Search icon
5. Filter icon appears at the RHS under the Search box
6. Select all the filters
**Expected Result:** Community stories box overlaps with the filter box. A
**Observed Result:**Box should not overlap. 
**Browser info:** Google chrome (Version 81.0.4044.122 (Official Build) (64-bit))
**GIF**
![overlap](https://user-images.githubusercontent.com/64552582/80635561-a7ae6700-8a21-11ea-8912-4d0e2970c171.gif)

**Comment by nithyaasworld** [comment]
Good Job @pranishi 

Just take care of the format of your bug. Have proper spacing between the sections like "Expected Result" and the step above it.
