### ISSUE TITLE
[Content Bug] Public Sector Page: Grammatical Errors

### ISSUE THREAD

**Issue by pranishi** [topcoder-platform/Training-Challenges#113]
**Steps to Reproduce:**
1. Navigate to "https://www.topcoder.com/public-sector/"
**Expected Result:** Team is a collective noun and "is" should be used along with team. And "to" to be used in place of "with" in the Screenshot attached below
**Observed Result:** "are" and "with" is used which are wrong
**Browser info:** Google chrome (Version 81.0.4044.122 (Official Build) (64-bit))
**Screenshot:**
![123](https://user-images.githubusercontent.com/64552582/80636763-8d758880-8a23-11ea-8611-0f31bb9581ba.png)

**Comment by nithyaasworld** [comment]
@pranishi Keep checking the Topcoder's Challenge listing page for new Bug Hunts and start participating on it for a Great QA experience and Cool Cash Prizes!

Please feel free to reach out to us in the challenge forum if you have any questions.

Join the Topcoder Slack channel, to get notifications about each new challenges.
