### ISSUE TITLE
[UI Bug] "Text-info" div is not loaded until press F11 or F12 button

### ISSUE THREAD

**Issue by papshoika** [topcoder-platform/Training-Challenges#119]
**Step to reproduce**
1. Open link https://www.topcoder.com/case-studies/land-o-lakes/
2. Scroll down to section with Allen Neire

**Actual result**
Information is not loaded, tested in two available browsers. Loads only after pressing F11 or F12
![image](https://user-images.githubusercontent.com/7930250/80791259-c2a3e700-8b99-11ea-9b65-76a9a4c2963c.png)
![image](https://user-images.githubusercontent.com/7930250/80791281-e1a27900-8b99-11ea-9a44-0e34743ddf69.png)

**Expected result**
Text-info loaded immediatly 
![image](https://user-images.githubusercontent.com/7930250/80791666-05b28a00-8b9b-11ea-9f24-29d9bda2c1b8.png)

**OS/Browser Information**
Ubuntu 16.04, Firefox Browser 75.0 (64-bit), Google Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Nice Work @papshoika
