### ISSUE TITLE
[Content bug] Spelling issue ("environme")

### ISSUE THREAD

**Issue by papshoika** [topcoder-platform/Training-Challenges#121]
**Steps to Reproduce:**
   1. Open the page https://help.topcoder.com/hc/en-us/articles/115008845167-What-is-a-Bug-Hunt-
2. Go to the end of the second section 

**Actual Result:**
Spelling issue in the word "environme" 
![image](https://user-images.githubusercontent.com/7930250/80793076-c7b76500-8b9e-11ea-8f73-0ba69884758c.png)
**Expected Result:**
Environment
**OS/Browser Information:**
Ubuntu 16.04, Firefox Browser 75.0 (64-bit), Google Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Nice Work @papshoika 

But make sure to provide screenshot of the whole screen along with the URL bar of the browser for your future bugs. This will help the developer/reviewer in reproducing/understanding the bug more easily.
