### ISSUE TITLE
[Functional bug] on submit button for this challenge

### ISSUE THREAD

**Issue by papshoika** [topcoder-platform/Training-Challenges#122]
**Steps to Reproduce:**
1. Go to https://www.topcoder.com/challenges/30108180/submit
2. Try to submit text file

**Actual Result:**
Wrong file type
**Expected result**
Instruction says "Find and post at least 3 valid bugs (each bug should be of different bug types) to Github. When you are done, **submit a text file** using the “Submit” button present in this page. In this text file include.." so it is expected that text file should be allowed
![image](https://user-images.githubusercontent.com/7930250/80793870-fa625d00-8ba0-11ea-9400-2de46a0273d6.png)
**OS/Browser Information:**
Ubuntu 16.04, Firefox Browser 75.0 (64-bit), Google Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Very Nice Observation @papshoika 

Currently only .zip file is supported for submission. I will change the Challenge Specification to say    to submit .zip file and not .txt file.

Go ahead and submit your .zip file for this Challenge.

Keep checking the Challenge Listing page for new Bug Hunt Projects and start participating in them for a Great QA Experience and Cool Cash Prizes.

Join the Slack Topcoder Community where you can get instant notifications for new Topcoder Projects.

All the very best!! @papshoika
