### ISSUE TITLE
[functional bug] topcoder site is not working on all browsers if logged in

### ISSUE THREAD

**Issue by geyuqiu** [topcoder-platform/Training-Challenges#123]
After opening the cache inspector (https://www.topcoder.com/challenges)
I just realized how many different caching options, topcoder is using 

sessionStorage, LocalStorage, Indexed DB, Cookies

The error can be resolved after clearing every cache and relogin again. 

We may need some unit testing those caching calls. 

<img width="1673" alt="Bildschirmfoto 2020-05-01 um 21 51 08" src="https://user-images.githubusercontent.com/4540661/80836879-f7458c00-8bf5-11ea-9326-3844de75ffad.png">

**Comment by geyuqiu** [comment]
can also be reproduced on Chrome and Firefox
<img width="1642" alt="Bildschirmfoto 2020-05-01 um 21 52 40" src="https://user-images.githubusercontent.com/4540661/80836948-19d7a500-8bf6-11ea-8379-6cc106a06180.png">

**Comment by geyuqiu** [comment]
and now suddenly: ...

![Bildschirmfoto 2020-05-01 um 22 06 17](https://user-images.githubusercontent.com/4540661/80837904-088f9800-8bf8-11ea-81e1-d5f258b80f0b.png)

**Comment by nithyaasworld** [comment]
Yeah I saw this happening too. I think Topcoder is looking into this already. Feel free to login any new issues that you would like to be resolved to this repo: https://github.com/topcoder-platform/community-app/issues (Please make sure to check it's not already reported)

And reach out to Support using the Support messenger or by writing to support@topcoder.com, anytime you need immediate help on something.

Feedback on the bug format:
Its always important to follow the Bug-Format provided in the respective Bug Hunt Challenge Instructions. Else our bug will not get the full-credit or sometimes rejected. So please take an extra care on this.

Keep checking the Challenge Listing page for Bug Hunt Projects and Start participating in it for a Great QA Experience and Cool Cash Prizes. Feel free to reach out to us in the Challenge forum for any queries. Join the Slack Topcoder Community Channel to get instant notification about all the New Challenges.

All the Very Best! @geyuqiu
