### ISSUE TITLE
[UI Bug] Footer overlaps datepicker

### ISSUE THREAD

**Issue by abishek-b** [topcoder-platform/Training-Challenges#124]
**Bug Title** : Footer overlaps datepicker in profile screen
**Steps to reproduce** : 
1) Go to profile screen and select Work options
2) Click on either Start date or End date inputs
**Actual Result** : Datepicker UI goes below the footer.
**Expected Result** : Datepicker UI should be on top
**Screenshot**:
![image](https://user-images.githubusercontent.com/16049229/81490093-590f9100-929b-11ea-9e5f-75e42473d4dd.png)
**Device/OS/Browser Information:**
Chrome Browser on Ubuntu

**Comment by nithyaasworld** [comment]
Good Job @abisuman
