### ISSUE TITLE
[Functional bug] I'm a customer button is not working

### ISSUE THREAD

**Issue by bruno973** [topcoder-platform/Training-Challenges#125]
# Steps : 

- Go on : https://www.topcoder.com/ without being logged in.
- Click on "I'm a customer"

# Actuel results :

When user click on "I'm a customer" is redirected to the same page.

# Expected results :

When user click on "I'm a customer"  is redirected to the part of the site who is made for customers

# Screencast :

[https://www.dropbox.com/s/uf9qtk3d0qskf5j/Bug%20i%27m%20a%20customer%20button.MP4?dl=0](url)

# Device

Iphone 6 IOS V 12.4.6 , Safari on IOS

**Comment by nithyaasworld** [comment]
Good Job in finding this bug @bruno973
