### ISSUE TITLE
[UX Usability] User can't swipe left or right the slider

### ISSUE THREAD

**Issue by bruno973** [topcoder-platform/Training-Challenges#127]
## Steps :

- Go on : https://www.topcoder.com/solutions/qa-testing/  .
- Scroll to the first slider 

## Actual results :
User has to click on the point downside the slider to see the next slide

## Expected results :
Some user may try to swipe left and swipe right the slider expecting to see the next slide, and not pay attention to the points downside the slider, and so miss next slides.

## Screencast :
https://www.dropbox.com/s/vqd8zaewcj1qan1/Bug%20Firefox%20UX%20slider.MP4?dl=0

## Device
Iphone 6 IOS V 12.4.6 , Firefox on IOS

**Comment by nithyaasworld** [comment]
Good Job @bruno973 

Keep checking the Challenge Listing page for new Bug Hunt Projects and start participating in them for a Great QA Experience and Cool Cash Prizes.

Join the Slack Topcoder Community where you can get instant notifications for new Topcoder Projects.

All the very best!! @bruno973
