### ISSUE TITLE
No Country Rank     

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/Training-Challenges#13]
1. Go to  "CODE" details: https://www.topcoder.com/members/Rokit12/details/?track=DEVELOP&subTrack=CODE
2. Under the "statistics" MENU
**ACTUAL RESULT:** The country rank does not show 
**EXPECTED RESULT:**  There should be country rank for the topcoder member.
CHECK THE IMG AND ZIP FILE 

Device/OS/Browser Information: Linux,Ubuntu
OS: Kali
Browser information:Chromium browser Version 73.0.3683.75 (Developer Build) built on Debian buster/side, running on Debian kali-rolling (32-bit)
![RANK](https://user-images.githubusercontent.com/37167721/69760768-6d8d2080-1176-11ea-801b-8f7709ebcc1b.jpg)

**Comment by nithyaasworld** [comment]
@Rokit12 This bug should come under Functional bug. 

Accessibility bug is anything related to [Accessibility](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility).

**Comment by Rokit12** [comment]
Thank you for the correction
