### ISSUE TITLE
[Functional bug]Contact us page is invalid ,404 error

### ISSUE THREAD

**Issue by TerryJLU** [topcoder-platform/Training-Challenges#131]
**Steps to Reproduce:**

1.Go to: https://www.topcoder.com/solutions/
2.Move to bottom
3.Click QUESTIONS? CONTACT US

**Actual Result:**
Get 404 error 

**Expected Result:**
Should show Contact us page or correct error message ，not 404

**Screenshots or screencast URL:**
https://drive.google.com/open?id=1_ffu44Kb9YGy6TOj-QGEBWQ-4W3X_A9M

**Comment by nithyaasworld** [comment]
@TerryJLU This video is same as your previous video and It doesn't have the details of the current bug. Can you please check again and provide the right screenshots/screencast?

**Comment by TerryJLU** [comment]
Hi
Fixed
https://drive.google.com/open?id=1_ffu44Kb9YGy6TOj-QGEBWQ-4W3X_A9M

Brs

**Comment by nithyaasworld** [comment]
Good catch @TerryJLU
