### ISSUE TITLE
[UX Usability] User can't swipe items left or right  in dashboard

### ISSUE THREAD

**Issue by TerryJLU** [topcoder-platform/Training-Challenges#132]
**Steps to Reproduce:**

1.Go to: https://www.topcoder.com/my-dashboard and login
2.Try to swipe MY ACTIVE CHALLENGES ,MY COMMUNITIES,SRMS

**Actual Result:**
Could not  swipe items

**Expected Result:**
It is better that User  can swipe items left or right  in dashboard

**Screenshots or screencast URL:**
![4](https://user-images.githubusercontent.com/19278622/82718251-f921dd00-9cd3-11ea-9866-f1471f7b10e5.jpg)

https://drive.google.com/open?id=17WUBvIn4Kzcbuymq0RCs43vVVEaqYJOu

**Comment by nithyaasworld** [comment]
Good Job @TerryJLU 

Please check the following pages to know about the current and upcoming QA Challenges and participate on them for Big prize money and Cool QA Experience.

- https://www.topcoder.com/challenges
- https://www.topcoder.com/community/pipeline
