### ISSUE TITLE
[Functional Bug] In user's language settings, the clear value button doesn't work

### ISSUE THREAD

**Issue by DrShaimaaAli** [topcoder-platform/Training-Challenges#133]
Steps to Reproduce:
1.Log in to TopCoder
2. Click on user name 
3. Click on settings in the drop-down menu
4. Click on "Language" in the left-side navigation
5. Select a langugae
6. Select a Spoken level
7. Hover over the little "x" that appears in the menu, a tooltip that says "Clear value" appears
8. Click on the "x" sign 

Actual Result:
Nothing happens

Expected Result: 
Should clear the value as the field is options

Screenshots or screencast URL:

![LanguageSettingsBug](https://user-images.githubusercontent.com/60110295/82764395-54d78d80-9ddc-11ea-9b28-77b0919ddfaf.png)

Device/OS/Browser Information:
 Google Chrome on both
Apple Mac OS X 10.9.5 and HP, Windows 10

**Comment by nithyaasworld** [comment]
Hey @DrShaimaaAli Can you please attach a Video of your bug as the bug is not obvious in the screenshot?

**Comment by DrShaimaaAli** [comment]
Sure, here it is
![LangSettingBug](https://user-images.githubusercontent.com/60110295/82944665-99446400-9f69-11ea-899b-4790fc553cdb.gif)

**Comment by nithyaasworld** [comment]
Good Job @DrShaimaaAli 

Please check the following pages to know about the current and upcoming QA Challenges and participate on them for Big prize money and Cool QA Experience.

- https://www.topcoder.com/challenges
- https://www.topcoder.com/community/pipeline
