### ISSUE TITLE
[Functional Bug] In Payments page, Learn, Get Started is invalid[404 error]

### ISSUE THREAD

**Issue by AkhilParim** [topcoder-platform/Training-Challenges#134]
**Steps to reproduce:**
1. Go to https://www.topcoder.com
2. Click on profile -> My Profile
3. Click on Payments
4. Hover on Learn and select Get Started

**Actual Result:**
404 error

**Expected Result:**
Should show Get Started page.

**Screenshots:**
<img width="1648" alt="Screenshot 2020-05-29 at 11 49 49 PM" src="https://user-images.githubusercontent.com/45338579/83292097-25bf8280-a207-11ea-8b6f-59efc5bf0b57.png">

**Device/OS/Browser Information:**
Safari
Apple Mac OS X 10.15.5

**Comment by nithyaasworld** [comment]
Great Catch @AkhilParim
