### ISSUE TITLE
[UI bug] When text size is increased, some characters are missing or cut off

### ISSUE THREAD

**Issue by AkhilParim** [topcoder-platform/Training-Challenges#137]
**Steps to reproduce:**
1. Go to https://www.topcoder.com
2. Click on hide button on the right bottom corner
3. Click on bigger text and increase the text size

**Actual result:**
Some text is cut off
(Some people may prefer bigger text but not missing text.

**Expected result:**
No text should be cut-off or just limit the bigger text to 2x (4x is not needed)

**Screenshots:**
<img width="1648" alt="Screenshot 2020-05-30 at 1 17 20 AM" src="https://user-images.githubusercontent.com/45338579/83299359-a3898b00-a213-11ea-940d-c44f2e289fbe.png">

**Device/OS/Browser Information:**
Safari
Apple Mac OS X 10.15.5

**Comment by nithyaasworld** [comment]
Well written expected result!
