### ISSUE TITLE
[UX / Usability bug] The green blinking mark on compete is irritating

### ISSUE THREAD

**Issue by AkhilParim** [topcoder-platform/Training-Challenges#138]
**Steps to reproduce:**
1. Go to https://www.topcoder.com

**Actual result:**
The green big blinking mark on compete(in any page) is irritating.

**Expected result:**
There's no need for that mark at least when user is in compete page
(It causes bad experience for the user)

**Screenshots:**
<img width="1648" alt="Screenshot 2020-05-30 at 1 37 37 AM" src="https://user-images.githubusercontent.com/45338579/83300893-6c68a900-a216-11ea-8ea7-3a51ab22cf11.png">

**Device/OS/Browser Information:**
Safari
Apple Mac OS X 10.15.5

**Comment by nithyaasworld** [comment]
Well done! @AkhilParim 

Please check the following pages to know about the current and upcoming QA Challenges and participate on them for Big prize money and Cool QA Experience.

https://www.topcoder.com/challenges
https://www.topcoder.com/community/pipeline
