### ISSUE TITLE
[UI bug]misalignment after increase text size

### ISSUE THREAD

**Issue by logoshot** [topcoder-platform/Training-Challenges#141]
**steps to reproduce**

- go to https://www.topcoder.com/
- open accessibility menu
- click bigger text two times
- scroll to the middle of the page

**actual result**
the link `explore solutions`  is misaligned

**expected result**
to appear in the middle of the green box

**screenshots**
![image](https://user-images.githubusercontent.com/34298372/83343232-184ee900-a32a-11ea-9cc6-28c9f609b34c.png)

**Device/OS/Browser Information**
laptop/win10/chrome

**Comment by nithyaasworld** [comment]
Good job @qunidad. But this bug should be reported along with the previous bug (#140 )as both use the same steps to reproduce. Its a good practice to group similar bugs together.
