### ISSUE TITLE
[Functional bug ] submissions count for a challenge shows one more than the actual number of submissions 

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/Training-Challenges#143]
### Steps to Reproduce
1. Go to https://www.topcoder.com/challenges/ tab
2. Register for "How to learn bug hunt" (https://www.topcoder.com/challenges/30108180) challenge 
3. Then check for the submissions tab in the challenge details page (https://www.topcoder.com/challenges/30108180?tab=submissions)
4. Check the count mentioned in the submissions tab

### Actual Result:
Count shown is always one more than the actual number of submissions listed on the tab.

### Expected Result: 
Submissions count should be same as the actual number of count listed on the page.

### Screenshots or screencast URL:
<img width="895" alt="Screenshot 2020-06-01 at 8 00 52 PM" src="https://user-images.githubusercontent.com/5712602/83420692-9acbcb80-a444-11ea-8ded-f250225362e4.png">
<img width="1397" alt="Screenshot 2020-06-01 at 8 02 28 PM" src="https://user-images.githubusercontent.com/5712602/83420703-9e5f5280-a444-11ea-8ce6-ed903a608bb9.png">

### Device/OS/Browser Information:
Device: MacBook pro 13 inch
OS: macOS Catalina 10.15.4
Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Good catch @ranjyotiprakash
