### ISSUE TITLE
[UI bug] User's avatar is broken in challenge forum UI

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/Training-Challenges#144]
### Steps to Reproduce

1. Go to https://www.topcoder.com/challenges/ tab
2. Register for "How to learn bug hunt" (https://www.topcoder.com/challenges/30108180) challenge
3. Click on Challenge Forum in challenge details (https://www.topcoder.com/challenges/30127241?tab=details)
4. Notice the user's avatar in the top right corner of the page in the forum

### Actual Result:
User's avatar of profile image is broken on the UI

### Expected Result:
User's avatar of profile image should be shown correctly.

### Screenshots or screencast URL:
<img width="1437" alt="Screenshot 2020-06-01 at 11 36 07 PM" src="https://user-images.githubusercontent.com/5712602/83439929-a7125180-a461-11ea-9fe1-3d5d8e348375.png">

### Device/OS/Browser Information:
Device: MacBook pro 13 inch
OS: macOS Catalina 10.15.4
Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Wonderful! @ranjyotiprakash 

Please check the following pages to know about the current and upcoming QA Challenges and participate on them for Big prize money and Cool QA Experience.

https://www.topcoder.com/challenges
https://www.topcoder.com/community/pipeline
