### ISSUE TITLE
[Functional bug] Broken link on Topcoder Marathon Guide article

### ISSUE THREAD

**Issue by nursoltan-s** [topcoder-platform/Training-Challenges#145]
Bug Title: "THE COMPLETE GUIDE TO TOPCODER MARATHON MATCHES – CURATED JUST FOR YOU!"
Steps to Reproduce:
1) Go to: https://www.topcoder.com/complete-guide-topcoder-marathon-matches-curated-just/
2) Find a link with title "cheat sheet".
3) Click on this link.

Actual Result:
Link redirects to "Event calendar" page.
Expected Result: 
Link should go to Nickolas's cheat sheet on how to practice MM matches.

Screenshots or screencast URL:
https://monosnap.com/direct/PzMmrw2p8odgRQahEB69lwgqMQKr49

Device/OS/Browser Information:
OS: Ubuntu 18.04
Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
@nursoltan-s You must try this challenge now: https://www.topcoder.com/challenges/30127241
