### ISSUE TITLE
[UI bug] "Register Now" option should not be shown to a logged in User on community page

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/Training-Challenges#146]
### Steps to Reproduce
1. Open topcoder.com in browser window
2. Login to your account by clicking on "Login" on the top right corner.
3. After logging in, Click on "COMMUNITY" button on this page.
4. After click , UI will redirect to "https://www.topcoder.com/community/learn" URL
5. Check the page's content.

### Actual Result:
There is a "Register Now" button available on the page, click on which redirects to the a New User Registration page.

### Expected Result:
"Register Now" should be available only to anonymous users who are logged in. It is un-necessary to show this button to an user who has already registered an is currently logged in.

### Screenshots or screencast URL:
<img width="1435" alt="Screenshot 2020-06-03 at 12 46 43 PM" src="https://user-images.githubusercontent.com/5712602/83608116-f3f94380-a599-11ea-9df5-3e6ff91403d9.png">

[Screen Recording 2020-06-03 at 12.49.49 PM.zip](https://github.com/topcoder-platform/Training-Challenges/files/4721619/Screen.Recording.2020-06-03.at.12.49.49.PM.zip)

### Device/OS/Browser Information:
Device: MacBook pro 13 inch
OS: macOS Catalina 10.15.4
Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Fantastic @ranjyotiprakash 

Please start participating on the Test-for-Success challenge. Challenge dates and more details are available here: https://www.topcoder.com/lp/test-for-success

**Comment by nithyaasworld** [comment]
Note 1: In the test-for-success challenge series, Exploratory is the 'Bug Hunt' Challenge-type and Regression is the "Test Case Execution" Challenge-type which you can easily do with the experience you have now.

Note 2: This challenge requires a different Bug-Report-format than any other Bug Hunts and needs high attention to catch new bugs. 

Good Luck!
