### ISSUE TITLE
[Functional bugs]- 404 error.The resource you are looking for does not exist in Topcoder community App :(

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/Training-Challenges#148]
Steps ; -
1. Enter the URL - https://topgear.topcoder.com/challenges/30127074
2. Search for challenge >> PenTest for APAC EquiTrak HK Testing
3. Click on Challenge Forum Tab >> First2Finish Questions
4. Now ,Mouse hover on COMPETE >>DEVELOPMENT CHALLENGES

Actual Result : 404 error.The resource you are looking for does not exist in Topcoder community App :(

Expected Result : Topcoder community app should load on click.

Note : User has already registered for the challenge {ab668685 - user}

![image](https://user-images.githubusercontent.com/61318135/84227412-ff042480-ab01-11ea-86ab-0c6c3e7d5664.png)

**Comment by ab668685** [comment]
Browser - Chrome version - Version 83.0.4103.97 and OS version - Windows 10

**Comment by nithyaasworld** [comment]
@ab668685 Good Job in finding this bug.
Just take care that the Title is very precise and not generic. A good title for this bug would be like "404 error when accessing COMPETE >>DEVELOPMENT CHALLENGES from forum page"

**Comment by ab668685** [comment]
@nithyaasworld Thank you .I will be taking care while raising bug .
