### ISSUE TITLE
[UI bug]On mousehover of sort icon - hashnumber appears

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/Training-Challenges#149]
Steps:-
1. Enter the URL : https://www.topcoder.com/
2. Select any challenge - 
3. Goto Submission Tab
4. Mousehover on sort(reorder) option of UserName , Submission Date ,Score

Actual Result : On mousehover of sort icon - hashnumber appears
Expected Result : On mousehover of sort icon - hash number should not appear.

![image](https://user-images.githubusercontent.com/61318135/84228943-f9a8d900-ab05-11ea-9bf4-421584067882.png)

**Comment by ab668685** [comment]
Browser - Chrome version - Version 83.0.4103.97 and OS version - Windows 10

**Comment by nithyaasworld** [comment]
Great find @ab668685 

CC: @Oanh-and-only-Oanh
