### ISSUE TITLE
No functionality to choose default (human avatar) once an avatar has been uploaded/ No functionality to remove an avatar #UX Bug

### ISSUE THREAD

**Issue by AnshuBhatt** [topcoder-platform/Training-Challenges#15]
Steps to Reproduce:

1. Login to Topcoder. 
2. Go to the user's profile page. Example: https://www.topcoder.com/settings/profile
3. Check for the Avatar under the 'Basic Info Tab'
4. Check if there is an option to remove the avatar if uploaded earlier(For instance, a user wants to remove his/her avatar, and wants to set the default human avatar back).

Actual:
There is no option to remove the avatar and set the default human avatar back.

Expected:
There should be a remove button available for the users to remove the avatar and set the default human avatar back

Screenshot
![Screenshot (1253)](https://user-images.githubusercontent.com/38535720/69850825-328a0a80-12a6-11ea-8b37-d57c5e770bee.png)
![Screenshot (1254)](https://user-images.githubusercontent.com/38535720/69850826-3322a100-12a6-11ea-87eb-4155f09c3353.png)

 

Device/OS/Browser Information:
Windows 10 Chrome Latest

**Comment by AnshuBhatt** [comment]
![Screenshot (1253)](https://user-images.githubusercontent.com/38535720/69852883-6c114480-12ab-11ea-8347-896e76d668d7.png)

**Comment by nithyaasworld** [comment]
**Nice Job @AnshuBhatt** in creating this bug exactly in the given format.

But it is most likely a UX bug (or an enhancement or a feature request) than a functional bug.

**Comment by AnshuBhatt** [comment]
Thank you mam for this information. I will correct it now.
