### ISSUE TITLE
[Functional bug]Submission button enabled even after Submission phase ended

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/Training-Challenges#150]
Steps:-
1. Enter the URL: https://www.topcoder.com/
2. Search the Challenge - CRM - Search and Validation Application Bug Hunt
3. Click on Shoe Deadline.
4. Verify the Submission phase Jun 10, 10:56
Note : Timezone is India

Actual Result : Submission button enabled even after Submission phase ended
Expected Result : 1.  Submission button should not be enabled as the submission phase is over.
2. a Please change the text from Registration to Registration Ends .As this confuses user when the challenge is getting over.
b. Change text Submission to  Submission End

![image](https://user-images.githubusercontent.com/61318135/84230716-40003700-ab0a-11ea-8065-5307ef6e727a.png)

**Comment by ab668685** [comment]
Browser - Chrome version - Version 83.0.4103.97 and OS version - Windows 10

**Comment by nithyaasworld** [comment]
Good job again @ab668685 

For the 2a and 2b, you can raise another ticket as the nature of those issues is different from the functional bug you are pointing out.

Please check the following pages to know about the current and upcoming QA Challenges.

https://www.topcoder.com/challenges
https://www.topcoder.com/community/pipeline
https://www.topcoder.com/lp/test-for-success

Good Luck!!
