### ISSUE TITLE
A link that leads to 404 Page-not-found error

### ISSUE THREAD

**Issue by littleduck24** [topcoder-platform/Training-Challenges#154]
![Screenshot (4)](https://user-images.githubusercontent.com/67413515/86020139-6d604680-ba1f-11ea-9fd8-a12c7c730090.png)
![Screenshot (5)_LI](https://user-images.githubusercontent.com/67413515/86020157-73eebe00-ba1f-11ea-84e0-2f9660775dde.jpg)

Bug Title: A link that leads to 404 Page-not-found error.
Steps to Reproduce:  Single Round Matches -> Learn More.
Actual Result: A link that leads to 404 Page-not-found error.
Expected Result: A link that leads to a functioning webpage or removal of the link if it is no-longer needed.
Device/OS/Browser Information: Google Chrome, Version 83.0.4103.106 (Official Build) (64-bit), Windows 10.
Bug Type: Functional Bug

**Comment by winterflame** [comment]
Hi @littleduck24 ,

When reporting a bug, please mention the link so that it would be easier for the reviewer to reproduce. Also, use the markdown to format the details.
