### ISSUE TITLE
Support Button overlaps writing on webpage.

### ISSUE THREAD

**Issue by littleduck24** [topcoder-platform/Training-Challenges#155]
Bug Title: Support Button overlaps writing on webpage.
Steps to Reproduce: QA Practice Challenge - Find Bugs on Topcoder page -> Details -> Scroll down.
Actual Result: Support button in bottom right hand corner overlaps the writing in the right hand column of the webpage.
Expected Result: Button could be fixed so the writing moves around it or the button could appear lower down the page to improve readability.
Device/OS/Browser Information: Google Chrome, Version 83.0.4103.106 (Official Build) (64-bit), Windows 10.
Bug Type: UI Bug.
![Screenshot (6)_LI](https://user-images.githubusercontent.com/67413515/86020520-eb245200-ba1f-11ea-98b1-13af5b3c4ae1.jpg)

**Comment by winterflame** [comment]
This is as designed.
