### ISSUE TITLE
[Functional Bug] There are no list of skill available when user want to add skill to his profile from settings

### ISSUE THREAD

**Issue by Farissk** [topcoder-platform/Training-Challenges#157]
**Steps:**
> 1. Open www.topcoder.com
> 2. Login with valid credential
> 3. Click Drop down button on the account button
> 4. Select Settings
> 5. Click Skills section
> 6. Type any skill on the text input to select skill
> 7. Notice that no skills available after user typing a skill

**Actual Result:** 
When user type any skill in the text input to select skill, user notice that there are no list of skill available when user want to add skill to his profile from settings
>> _Notes:_
>> _- The only workaround to add or change skills is from "Update your profile now" hyperlink from PAYMENT POLICIES AND INSTRUCTIONS thrive_

**Expected Result:**
After user typing any skill, for example "testing", the related skill result should be displayed in the drop down menu

**Attachment:**
![Untitled](https://user-images.githubusercontent.com/67651640/86161837-139f6f80-bb38-11ea-924f-7ee3f8bdb1aa.png)

**Info:**
- Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Windows 10

**Comment by winterflame** [comment]
Unable to reproduce. 
![skill](https://user-images.githubusercontent.com/4590317/87169773-05eda500-c303-11ea-9d59-81f3af1ec3f7.jpg)
