### ISSUE TITLE
Categorized article still has uncategorized tag

### ISSUE THREAD

**Issue by WeiWeic6222848** [topcoder-platform/Training-Challenges#158]
Steps to Reproduce:
visit https://www.topcoder.com/category/uncategorized/
Actual Result:
Articles with multiple tags, one of the tags is "uncategorized"
Expected Result:
Articles with one only tag which is uncategorized
Screenshots or screencast URL:
![image](https://user-images.githubusercontent.com/22558527/86494132-58174f00-bd74-11ea-8263-052fcee00375.png)
Device/OS/Browser Information:
Device: 
Generic PC,
Windows 10
Chrome 83.0.4103.116

**Comment by winterflame** [comment]
Hi @WeiWeic6222848 ,

1) This can be an enhancement.
2) Regarding the bug report: it should use markdown to format the input, like this one: https://github.com/topcoder-platform/Training-Challenges/issues/1
