### ISSUE TITLE
No cancel button available when uploading an avatar

### ISSUE THREAD

**Issue by AnshuBhatt** [topcoder-platform/Training-Challenges#16]
**Steps to Reproduce:**

1. Login to Topcoder
2. Go to any user's settings page under the profile tab. Example: https://www.topcoder.com/settings/profile#basic-info
3. Under the basic info tab, click on "Upload a new Avatar'
4. Choose an image type file.
5. Check if there is an option to cancel the image upload in between the uploading process.

**Actual:**
There is no option to cancel the image upload in between. The user needs to wait until the image uploading process is completed before selecting any new image.

**Expected:**
There should cancel button available for the user to easily cancel the new image uploading process in between.

**Device/OS/Browser Information:**
Windows 10

**Screenshot**
![Screenshot (1256)](https://user-images.githubusercontent.com/38535720/69852758-1c327d80-12ab-11ea-8dbc-353fba9a3110.png)
 Chrome Latest

**Comment by nithyaasworld** [comment]
Browser info 'Chrome Latest' is present at the end. Just make sure that it is under the proper section like in the sample bug.

**Comment by AnshuBhatt** [comment]
Thank you mam for this information. I will correct it now.
