### ISSUE TITLE
In Project UBahn | Bug Hunt Submissions Tab  count is shown as 1 but there is no submission yet

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/Training-Challenges#161]
**Steps to Reproduce:** 
1.Navigate to challenges section on topgear.
2.Navigate to Project UBahn | Bug Hunt.
3.Verify Submission tab->In submission tab count is shown as 1 but there is no submission.

**Actual Result:** In submission tab count is shown as 1 but there is no submission.

**Expected Result**: If there are no submission then count should be displayed as 0.
Screenshots or screencast URL: 
![image](https://user-images.githubusercontent.com/68163678/87237921-b3eb7300-c419-11ea-9421-8c33be978025.png)

**Device/OS/Browser Information:** 
Device: Laptop
OS:Windows 10
Browser:Chrome

**Comment by winterflame** [comment]
This is a known issue, see https://github.com/topcoder-platform/Training-Challenges/issues/143
