### ISSUE TITLE
[Functional Bug] Unable to select the all date ranges

### ISSUE THREAD

**Issue by Scorpio1987** [topcoder-platform/Training-Challenges#164]
Steps to Reproduce: 
1) Go to topcoder.com
2) After login go to https://www.topcoder.com/settings/profile
3) Select work, try to select the range.
<img width="1920" alt="Screen Shot 2020-07-17 at 12 43 02 PM" src="https://user-images.githubusercontent.com/5514141/87827057-dffa6000-c82e-11ea-8324-f54b86de4adf.png"> 

Actual Result:  Unable to select dates from 3 row onwards. 

Expected Result:  Should be able to select all the dates.

Device/OS/Browser Information: Macbook Pro, OS X, Chrome 84.0.4147.89

**Comment by winterflame** [comment]
See #124
