### ISSUE TITLE
Payment: Payment table not aligned properly #UI bug

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/Training-Challenges#17]
Steps to Reproduce:

1. Go to https://www.topcoder.com/challenges/
2. Enter user credentials and click the login button.
3. Hover over the member profile.
4. Click Payments.
5. Check the Payment table alignment.

Actual Result:
Payment Table is not aligned properly.

Expected Result:
The payment table should be aligned properly.

Device/OS/Browser information:
Windows 7 Firefox latest.

Screenshot:

![Payment_table](https://user-images.githubusercontent.com/55895538/69874001-f1aee780-12df-11ea-90e6-30613cfe03a2.PNG)

**Comment by nithyaasworld** [comment]
Good Job @sandhiyakavi in following the format.

Can you describe exactly what is not aligned properly?

**Comment by sandhiyakavi** [comment]
I mean the table header (Net payment ).

**Comment by nithyaasworld** [comment]
Ok, This will be very minor but good to report.
