### ISSUE TITLE
Request a Visa Letter: Footer not aligned to the bottom #UI bug

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/Training-Challenges#18]
Steps to Reproduce:

1. Go to https://www.topcoder.com/challenges/
2. Enter user credentials and click the login button.
3. Hover over the member profile.
4. Click Settings.
5. Click the Preference menu
6. Click the Invitation letter sidebar menu.
7. Check the Footer alignment.

Actual Result:
Footer not aligned to the bottom.

Expected Result:
The footer should be aligned to the bottom.

Device/OS/Browser information:
Windows 7 Chrome latest.

Screenshot:

![Request a visa letter](https://user-images.githubusercontent.com/55895538/69875317-dbeef180-12e2-11ea-94b0-53dc4fc08b3f.PNG)

**Comment by nithyaasworld** [comment]
Good Job in finding this bug @sandhiyakavi
