### ISSUE TITLE
Forum User settings: No Success/Failure message is displayed on clicking the Save button #UX bug

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/Training-Challenges#19]
Steps to Reproduce:

1. Go to https://www.topcoder.com/challenges/
2. Enter user credentials and click the login button.
3. Hover over the Community menu.
4. Click Forums.
5. Click the User Settings link.
6. Make changes and click the Save button.

Actual Result:
No Success/Failure message is displayed on clicking the Save button.

Expected Result:
Success/Failure message should be displayed on clicking the Save button.

Device/OS/Browser information:
Windows 7 Chrome latest.

Video:

[Forum User settings.zip](https://github.com/topcoder-platform/Training-Challenges/files/3905663/Forum.User.settings.zip)

**Comment by nithyaasworld** [comment]
Good job @sandhiyakavi  in classifying the bug to the right category!
