### ISSUE TITLE
Not accepting any email(Functional Bug)

### ISSUE THREAD

**Issue by rajnish172** [topcoder-platform/Training-Challenges#223]
**STEPS TO REPRODUCE**
1. Go to http://www.topcoder.com/
2. just entering this website a pop-up appeared "to download an ebook"
3. enter your details
4. when you hit submit it will show error "Please enter your work email address"
5.after this you can enter any number of email id but same result it will give
 
**ACTUAL RESULT**
Please enter your work email address

**EXPECTED RESULT**
ebook downloading should have started  or should have transferred to ebook download page 

**SCREENSHOTS**
![Screenshot (148)](https://user-images.githubusercontent.com/42020921/124353697-a54b2c80-dc25-11eb-8e45-944480b1184e.png)
![Screenshot (149)](https://user-images.githubusercontent.com/42020921/124353700-aa0fe080-dc25-11eb-8bf4-72b83d6f61ac.png)

**BROWSER INFORMATION**
google chrome
Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
@rajnish172 The field accepts only work email addresses and not outlook.
