### ISSUE TITLE
On customer success page - Podcast has video display but on click it is audio

### ISSUE THREAD

**Issue by sharma-sajal** [topcoder-platform/Training-Challenges#235]
Bug Title: On customer success page - Podcast has video display but on click it is audio

Steps to Reproduce:
Open browser on your system, preferably Google Chrome
Access the URL - https://www.topcoder.com/
Go to the Customer success section
Observe the Wellmark Podcast

Expected Result -
- Go to the Customer success section
- Observe the Wellmark Podcast section with audio image
- On click of image a podcast is launched

Actual Result:
- Go to the Customer success section
- Observe the Wellmark Podcast
- A video image is displayed for Wellbeing
- On click of video image a podcast is launched

Screenshots or screencast URL: 
![Topcoder  - Podcast dispay video image](https://user-images.githubusercontent.com/3356030/127504459-29bc9fcb-ca9a-41e3-90e4-8d7ae6f924b8.jpg)
![Topcoder  - Podcast dispay video image - 1](https://user-images.githubusercontent.com/3356030/127504489-e58f4cb8-b830-4f24-818d-22dc8f2bc345.jpg)

Screenshot attached

**Comment by nithyaasworld** [comment]
This is as per design @sharma-sajal
