### ISSUE TITLE
Error 404 in the onboarding members  

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/Training-Challenges#24]
Go to: https://www.topcoder.com/member-onboarding
ACTUAL RESULT: ERROR 404 in the members onboarding tab
![404](https://user-images.githubusercontent.com/37167721/69901769-11edad80-1397-11ea-804e-9e105a464a89.jpg)

EXPECTED RESULTS: There should be no animated image at that point

Check the file below

**Comment by nithyaasworld** [comment]
Hey @Rokit12 
1. I am not able to reproduce the bug by following the steps provided. Please check it
2. Please follow the exact same format as in the Sample bug. Following the format provided in the Bug hunt is very important. In some bug hunts, the submitter will be penalized if the given format is not followed. So please take extra care on that part.

You are doing good on everything else!

**Comment by Rokit12** [comment]
checking it again

**Comment by Rokit12** [comment]
I have updated the link. Kindly check
