### ISSUE TITLE
forms with loading error

### ISSUE THREAD

**Issue by leon1247** [topcoder-platform/Training-Challenges#246]
**Steps to play:** <visit "topcoder.com", on the main page click on the form link "book a demo" or "get your copy" >

**Actual result:** < misaligned, unframed form, improper background color and even overlapping sentences >

**Expected result:** <form aligned, framed and with a good design>

**Screenshots:**
![bug de iu  topcode](https://user-images.githubusercontent.com/88126714/131398114-e1a5b9c8-8205-4205-9489-a80a3e144dcd.jpg)
![Sem título](https://user-images.githubusercontent.com/88126714/131398372-e6204e5d-9e63-4fc9-92f5-3adacdf9c87f.png)

**device / operating system / browser:** <asus notebook / windows 10 / gloogle chrome>

**ui bug **

**Comment by nithyaasworld** [comment]
@leon1247  Is this bug still reproducible? It is not reproducible to me. It loads good. Please attach a video (use any screen recorder to record the screen) if its still an issue. Make sure to start from where you access the www.topcoder.com in the video and also have the browser console opened while recording the video, so we can see the errors displayed in the console if any.  If its not reproducible, you can close this bug.

Feel free to post if you have any queries.

![image](https://user-images.githubusercontent.com/5114190/131664091-147ae123-2087-4fac-94b3-9728367a9dab.png)

**Comment by leon1247** [comment]
Yes. the bug no longer reproduces!
