### ISSUE TITLE
Unable to navigate to Home page (www.topcoder.com) when the user visits the 'My Projects' page (www.connect.topcoder.com) # Functional

### ISSUE THREAD

**Issue by vijyanandkumar** [topcoder-platform/Training-Challenges#26]
Unable to navigate to Home page (www.topcoder.com) when the user visits the 'My Projects' page (www.connect.topcoder.com)

Steps :
1. Login to www.topcoder.com
2. Click on My Projects tab on home page.
3. Connect.topcoder.com page is loaded.
4. When user attempts to go back to topcoder.com by clicking back button in browser , the page keeps reloading the connect.topcoder.com page only and does not navigate back to www.topcoder.com.

Expected : 
www.topcoder.com page should be loaded on click of back button in browser.

Device : 
Desktop - Windows 10 / Chrome browser

![image](https://user-images.githubusercontent.com/58428770/69962200-7ba2be80-1533-11ea-93f0-0385ea9b285f.png)

**Comment by nithyaasworld** [comment]
Nice find! @vijyanandkumar
