### ISSUE TITLE
UI Hyperlink issue- "Click here" Link not hyperlinked in contact us page 

### ISSUE THREAD

**Issue by 20267226** [topcoder-platform/Training-Challenges#269]
Steps to reproduce:
1) Go to https://www.topcoder.com/how-it-works/
2) Scroll to the bottom of the page.
3) IN that click on contact us
4)Scroll to the bottom of the contact page.
5)The click here link to accept the terms and policy is not hyperlinked.

Actual Result:
![image](https://user-images.githubusercontent.com/91531047/135066997-230a0493-ba26-4a79-bde1-48f8907ef4c6.png)

Expected Result:
The click here link to by hyperlinked and user should be able to accept the terms and policy.

**Comment by nithyaasworld** [comment]
They are describing about the 'Click Here' button present in the form. So it is not hyperlinked @20267226
