### ISSUE TITLE
UI Functional bug: An invalid email with invalid domain is accepted in email field in contact us page

### ISSUE THREAD

**Issue by 20267226** [topcoder-platform/Training-Challenges#270]
Steps to Reproduce:
1) Go to topcoder.com
2) Scroll to the end of the page and click on contact us link
3) In contact us page, give invalid mail with invalid domain in the email field.
4)Click on click here 
5) It gets saved.

Actual Result:
![image](https://user-images.githubusercontent.com/91531047/135071608-9f1fdd7d-0107-45ad-a5fb-b0f0f58ff625.png)
![image](https://user-images.githubusercontent.com/91531047/135071907-a27fda88-d614-48b2-88f8-d4e1237c3b90.png)

Expected Result:
An error message should be displayed for the invalid domain in invalid email entered.

**Comment by nithyaasworld** [comment]
Its not necessary to validate the existence of the email @20267226 

But if the email format is not validated, it could be considered as an issue. But in the current form, they are validating for bad email format.

![image](https://user-images.githubusercontent.com/5114190/135141225-20968fb1-94b7-4675-a174-b6ad95ebb7d4.png)

**Comment by nithyaasworld** [comment]
@20267226 Please try again.
