### ISSUE TITLE
[Functional bug]: Dead link on Company Jobs page

### ISSUE THREAD

**Issue by nursoltan-s** [topcoder-platform/Training-Challenges#30]
**Bug Title**: Dead link on Company Jobs page.
**Steps to Reproduce**:
1. Go to 'https://www.topcoder.com/company/jobs' page.
2. Click on 'Wipro' link under section under "Room to Grow". 
3. Link doesn't work.

**Actual Result**:
Link is actually dead and goes top of page.

**Expected Result**: 
Link should go to Wipro website.

**Screenshots or screencast URL**:
![Screenshot from 2019-12-03 11-24-59](https://user-images.githubusercontent.com/7783676/70018022-c5d18180-15bf-11ea-91c8-cd30f2b069a5.png)

**Device/OS/Browser Information**:
OS: Ubuntu 18.04, 64 bit
Browser: Version 78.0.3904.108

**Comment by nithyaasworld** [comment]
Good Job @nursoltan-s in following the given information.

You are ready to participate in future bug hunts!
