### ISSUE TITLE
Content alignment in the thrive page

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/Training-Challenges#32]
Go to: https://www.topcoder.com/thrive/   then go to Featured articles
ACTUAL RESULT: The featured articles are not well aligned

EXPECTED RESULTS: The content should be well aligned one after another with the same height
![align](https://user-images.githubusercontent.com/37167721/70125944-f6312280-1688-11ea-9580-b17fe5bd9930.jpg)

Check the file below

Device/OS/Browser Information: Linux,Ubuntu
OS: Kali
Browser information: Chromium Browser,Version 73.0.3683.75 (Developer Build) built on Debian buster/side, running on Debian kali-rolling (32-bit)

**Comment by nithyaasworld** [comment]
I think it is how it is designed. I am marking this as Accepted as you have provided all the necessary info in the bug.
