### ISSUE TITLE
Error on Saving Filter option in challenges form.  

### ISSUE THREAD

**Issue by gayand123** [topcoder-platform/Training-Challenges#33]
Error on Saving Filter option in challenges form. 

Functional bug

Steps to Reproduce:
go to challenges window. ( https://www.topcoder.com/challenges )
select the filters option.
enter values for text boxes.
select save filter option.

Actual Result:
displaying error message and data is not saved. 
Expected Result: 
the filter should be saved. 

Screenshots or screencast URL:
![saving error](https://user-images.githubusercontent.com/32235212/70251042-d8f17680-17a4-11ea-84eb-f1c11aedebde.png)
![savingerror_2](https://user-images.githubusercontent.com/32235212/70252037-afd1e580-17a6-11ea-88df-bc7eef7ebb15.png)

Device/OS/Browser Information:
Google Chrome
Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Good Job @gayand123 in finding this bug!

Just make sure to Number the steps.
