### ISSUE TITLE
Date in footer should be 2019

### ISSUE THREAD

**Issue by shubham-dota** [topcoder-platform/Training-Challenges#37]
Bug Title: Wrong date in the footer  
Steps to reproduce: visit (https://topgear-app.wipro.com/home1)
Actual Result: © Copyright 2018 by Wipro Ltd
Expected Result: © Copyright 2019 by Wipro Ltd
Screenshots or screencast URL: https://topgear-app.wipro.com/home1
Device/OS/Browser Information:  OS: Windows 10, Browser: Chrome
![topgear1](https://user-images.githubusercontent.com/58764896/70790055-44959e00-1dba-11ea-9d89-d961aa24028f.png)

**Comment by nithyaasworld** [comment]
Hi, the domain reported is wipro.com which is not in scope. Can you try in topcoder.com domain?
