### ISSUE TITLE
Profile page, save setting button doesnt get enabled

### ISSUE THREAD

**Issue by mrShaolin** [topcoder-platform/Training-Challenges#42]
Steps to Reproduce:http:://connect.topcoder.com/settings/profile
Actual Result: You cannot save changes as the save settings button is not enabled
Expected Result: You should have a save setting button enabled that persists the profile changes
Screenshots or screencast URL: http:://connect.topcoder.com/settings/profile
Device/OS/Browser Information:Mac Mini/MacOS 10.15.1/Chrome
Functional Bug

**Comment by nithyaasworld** [comment]
Please provide more detailed steps to reproduce. I am not able to reproduce the issue by following the steps provided.

Please refer [sample bugs.](https://github.com/topcoder-platform/Training-Challenges/issues?q=is%3Aissue+is%3Aopen+label%3A%22Sample+Bug%22)
