### ISSUE TITLE
Icon Parts Are Not Covering Fully

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/Training-Challenges#44]
1. Go To www.topcoder.com

2. Scroll Down Mouse Below & Click On Each & Every Icon Then Observe

3. See The Screencast.
[Parts Are Not Covering Fully.mp4.zip](https://github.com/topcoder-platform/Training-Challenges/files/3992812/Parts.Are.Not.Covering.Fully.mp4.zip)

4. Actual Result: Icon Parts Are Not Covering Fully

5. Expected Result: Icons Should Be Covered Fully.

6. Device: Laptop

7. OS: OS Version macOS High Sierra 10.13.6 (17G6029)

8. Browser Information: Browser Version Google Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Nice job in finding this bug @devsreekrishna 

Please just make sure to follow the format like said earlier.
