### ISSUE TITLE
After Clicking On See More Its Going To Only One Page Talent As A Service Page Only

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/Training-Challenges#45]
1. Go To www.topcoder.com

2. Click On See More Icon More Than One Time Then See & Observe.

3. See The Screencast
[See More 1.mp4.zip](https://github.com/topcoder-platform/Training-Challenges/files/3992841/See.More.1.mp4.zip)

4. Actual Result: Its Going On Only One Page Talent As A Service Page Only.

5. Expected Result: Either It Should Go To Different Page Or It Should Not Show See More Icon.

6. Device: Laptop

7. OS: OS Version macOS High Sierra 10.13.6 (17G6029)

8. Browser Information: Browser Version Google Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Yeah, it is because of #43
