### ISSUE TITLE
Alignment Issue Below Explore Our Talent

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/Training-Challenges#46]
1. Go To www.topcoder.com

2. Click On See More Icon Then Scroll Down Mouse To Explore Our Talent & Observe

3. See The Screenshot
[Alignment Issue.png.zip](https://github.com/topcoder-platform/Training-Challenges/files/3992862/Alignment.Issue.png.zip)

4. Actual Results: View Profile Icons Are Not Aligned Properly.

5. Expected Result: View Profile Icons Should Be Aligned Properly

6. Device: Laptop

7. OS: OS Version macOS High Sierra 10.13.6 (17G6029) 

8. Browser Information: Browser Version Google Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
May be, that is how its designed! No issues as long as the profile cards are of same size.
