### ISSUE TITLE
Sentence/Words Some Parts are Cutting

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/Training-Challenges#47]
1. Go To www.topcoder.com

2. Click On Community Then Scroll Down Mouse Below To Trending At Topcoder & See

3. See The Screenshot
[Some Parts Are Cutting.png.zip](https://github.com/topcoder-platform/Training-Challenges/files/3992898/Some.Parts.Are.Cutting.png.zip)

4. Actual Result: Sentence/Words Some Parts Are Cutting

5. Expected Result: Sentence/Words Should Be Seen Fully.

6. Device: Laptop

7. OS: OS Version macOS High Sierra 10.13.6 (17G6029)

8. Browser Information: Browser Version Google Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Nice find @devsreekrishna 

Just make sure to follow the format as in the [sample bugs](https://github.com/topcoder-platform/Training-Challenges/issues?q=is%3Aissue+is%3Aopen+label%3A%22Sample+Bug%22)
