### ISSUE TITLE
Grammatical Error There In Sentence Member programs, incentives, and more

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/Training-Challenges#48]
1. Go To www.topcoder.com

2. Select Community Then Scroll Down Mouse To Connect With Us & See

3. See The Screenshot
[Member.png.zip](https://github.com/topcoder-platform/Training-Challenges/files/3992903/Member.png.zip)

4. Actual Result: Its Showing Sentence As Member programs, incentives, and more

5. Expected Result: It Should Be Sentence As Member programs, incentives and more

6. Device: Laptop

7. OS: OS Version macOS High Sierra 10.13.6 (17G6029)

8. Browser Information: Browser Version Google Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Just make sure to follow the format as in the [sample bugs](https://github.com/topcoder-platform/Training-Challenges/issues?q=is%3Aissue+is%3Aopen+label%3A%22Sample+Bug%22)
