### ISSUE TITLE
[UX Bug]"New Offering" banner should not be shown again after once close

### ISSUE THREAD

**Issue by hy-shuo** [topcoder-platform/Training-Challenges#49]
**Bug Title:** "New Offering" banner should not be shown again after once close

**Steps to Reproduce:**
1. Go to '[https://www.topcoder.com/](https://www.topcoder.com/)' page.
2. We can see the "New Offering" purple banner on top of this page.
3. Click on the little "X" on the right hand side of this banner.
4. Refresh this page, use F5 or Ctrl+R or click "reload" on browser
5. We can see the "New Offering" purple banner again.

**Actual Result:**
We will see the banner again after we close it.

**Expected Result:** 
After click the close button, next time open topcoder homepage, we shoule not see that banner again.

**Screenshots or screencast URL:**
![image](https://user-images.githubusercontent.com/38638677/71542124-79792780-295a-11ea-9381-43fbb61c49d1.png)

**Device/OS/Browser Information:**
Laptop with Windows 10 OS
Chrome browser 79.0.3945.88

**Comment by nithyaasworld** [comment]
**Format is perfect!!** Just dont need to include the Bug Title in the description
