### ISSUE TITLE
video can not open again[Functional bug]

### ISSUE THREAD

**Issue by hy-shuo** [topcoder-platform/Training-Challenges#50]
**Bug Title:** video can not open again in homepage

**Steps to Reproduce:**
1. Go to [https://www.topcoder.com/](https://www.topcoder.com/)
2. Click the green video play button
3. Close the playing window
4. Now the green video play button is invalid, can not open that video playing window again.

**Actual Result:**
Can not open the video again

**Expected Result:** 
Should be able to open the video again

**Screenshots or screencast URL:**
1. 
![image](https://user-images.githubusercontent.com/38638677/71542272-49328880-295c-11ea-93d9-0a0f7ecdc4d0.png)
2. 
![image](https://user-images.githubusercontent.com/38638677/71542277-5d768580-295c-11ea-984b-256b4e071be2.png)
3. 
![image](https://user-images.githubusercontent.com/38638677/71542284-87c84300-295c-11ea-9d1f-58ece9a16af0.png)

**Device/OS/Browser Information:**
Windows 10 Chrome Latest

**Comment by nithyaasworld** [comment]
As this bug cannot be validated by looking at the screenshot, highly recommend to attach video of the bug.
