### ISSUE TITLE
[UI Bug] Landing page - Customer Success Section button not styling correctly

### ISSUE THREAD

**Issue by Practess** [topcoder-platform/Training-Challenges#52]
**Steps to Reproduce:**

1. From an iPhone 6, go to Safari
2. Go to www.topcoder.com
3. Scroll down home page to the section with a header reading "Our Customer, Their Success"
4. Below this header is a button reading "View More Case Studies"

**Actual Result:**
The button text is styling so that 3 of the 4 words display within the button border and 1 word does not

**Expected Result:** 
All the button text should be visible from the button

**Screenshots or screencast URL:**
[Screenshot](https://github.com/Practess/Topcoder-Challenge-Assets/blob/master/Landing%20page%20-%20Customer%20Success%20Section%20button%20not%20styling%20correctly.JPG)

**Device/OS/Browser Information:**
iPhone 6/MacOS/Safari

**Comment by nithyaasworld** [comment]
@Practess Can you please paste the screenshot instead of the screenshot-link?

**Comment by nithyaasworld** [comment]
@Practess Please paste the screenshot for me to further assess the bug. I do not have access to see the Screenshot-link.
