### ISSUE TITLE
[FUNCTIONAL] Settings ->Profile - Unable to add 'safari' as a skills after adding 6 skills

### ISSUE THREAD

**Issue by Practess** [topcoder-platform/Training-Challenges#53]
**Steps to Reproduce:**
1. Register for a Topcoder account
2. Once you have been authenticated, follow the prompts to edit your profile settings
3. Scroll does left side navigation menu to SKILLS
4. Starting with 0 skills, search in dropdown for HTML
5. Click Add skill button.
6. Search in dropdown for CSS.
7. Click Add skill button.
8. Search in dropdown for Bootstrap.
9. Click Add skill button.
10. Search in dropdown for Wordpress.
11. Click Add skill button and green saved confirmation displays.
12. Search in dropdown for trello.
13. Click Add skill button and green saved confirmation displays.
14. Search in dropdown for Docker.
15. Click Add skill button and green saved confirmation displays.
16. Search in dropdown for safari.
17. Click Add skill button.

**Actual Result:**
Nothing happens
**Expected Result:**
A green saved confirmation displays.
**Screenshots or screencast URL:**
[Screenshot](https://github.com/Practess/Topcoder-Challenge-Assets/blob/master/Profile%20Settings%20-%20unable%20to%20add%20safari%20to%20Skills%20list%20after%20adding%206%20skills.JPG)
**Device/OS/Browser Information:**
Desktop/Windows 10 Pro/Chrome Latest

**Comment by nithyaasworld** [comment]
Hey @Practess Please provide us a video and attach it to this bug. Use any screen-recording tool of your choice.
