### ISSUE TITLE
[CONTENT] Privacy Policy Page: duplicated words

### ISSUE THREAD

**Issue by Practess** [topcoder-platform/Training-Challenges#54]
**Steps to Reproduce:**
1. Register for a new account using Github
2. Go to your email and validate the account.
3. From the email confirmation page on Topcoder, scroll to the bottom of the page.
4. Click the link to the Privacy Policy
5. Review the language in the first paragraph.

**Actual Result:**
A content repetition of "to the" in paragraph 1.
**Expected Result:**
Content does not include duplicated words.
**Screenshots or screencast URL:**
[Screenshot](https://github.com/Practess/Topcoder-Challenge-Assets/blob/master/Privacy%20Policy%20-%20content%20duplicate%20words.JPG)
**Device/OS/Browser Information:**
Desktop/Windows 10 Pro/Chrome Latest

**Comment by nithyaasworld** [comment]
@Practess Please paste the screenshot into this Bug Report. Please reach out to me in the forum if you need any help on this.
