### ISSUE TITLE
[FUNCTIONAL] Cannot submit in Bug hunt Challenge

### ISSUE THREAD

**Issue by docsa** [topcoder-platform/Training-Challenges#55]
**Bug Title:** cannot submit answer from Dashboard

**Steps to Reproduce:**  
- login with my id : docsa
- Click "*Community*" then "*Dashboard*"
- My active challenge displays (Screenshot 1) 
- Click "*Submit*"
**Actual Result:**  
blank screen with grey background
Error messages in console : 
`TypeError: Cannot read property 'currentPhases' of null`

**Expected Result:**  
Submit bug form 
**Screenshots or screencast URL:**  
https://www.topcoder.com/challenges/30108180/submit
**Device/OS/Browser Information:**  
MacBook Air / MacOs 10.14.16 / Chrome 79.0.3945.88

![Screenshot 1](https://user-images.githubusercontent.com/25287625/71626500-db9d8b00-2bed-11ea-9206-29d939fb38e7.jpg)

![Screenshot 2](https://user-images.githubusercontent.com/25287625/71626515-ed7f2e00-2bed-11ea-89c1-06af6de9bb01.jpg)

**Comment by nithyaasworld** [comment]
@docsa Great Catch! 

Only thing is that, the URL provided is the URL where the bug is noticed. But we asked for the Screenshot or the Video URL(if you have uploaded the video into any other platform).
