### ISSUE TITLE
[UI] Broken link picture in arena Dashboard

### ISSUE THREAD

**Issue by docsa** [topcoder-platform/Training-Challenges#56]
**Bug Title:** Broken link in Competition Arena  Dashboard 

**Steps to Reproduce:**  
- login with my id : docsa
- Click "*Community*" then "*Compete*" and "*Competitive Programming*'

**Actual Result:**  
Broken link picture 
Error messages in console : 
`GET https://apps.topcoder.comnullnull/ net::ERR_NAME_NOT_RESOLVED`

**Expected Result:**  
Profile picture display

**Screenshots or screencast URL:**  
[https://arena.topcoder.com/#/u/dashboard](https://arena.topcoder.com/#/u/dashboard)

**Device/OS/Browser Information:**  
MacBook Air / MacOs 10.14.16 / Chrome 79.0.3945.88

![capture 2019-12-31 à 17 21 38](https://user-images.githubusercontent.com/25287625/71627488-f9b9ba00-2bf2-11ea-9cf8-b65a4e4b6dbc.jpg)

**Comment by nithyaasworld** [comment]
Good Job @docsa
