### ISSUE TITLE
[ UI bug ] Some UI not completely loaded in resource page until refresh

### ISSUE THREAD

**Issue by OfficialBafisi** [topcoder-platform/Training-Challenges#59]
**Steps to Reproduce:**
1. Navigate to the landing page / Home page https://www.topcoder.com/
2. Click on **more** button
3. Click on the Resources
4. Some UI is not displayed when first landing on resources page
5. Refresh the page
6. Now the UI is shown on resources page

**Actual Result:**
Some UI (Mostly colors) is not shown until a refresh

**Expected Results**
All of the UI to be shown on the page

**Screencast**
https://drive.google.com/file/d/16rj5YHFsIVTxm8oFjoKoA5UHzBFI986w/view

**Device/OS/Browser Information:**
Google Chrome
Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Wonderful Reporting @OfficialBafisi 

Thank You!
