### ISSUE TITLE
[UX / Usability]Home Navigation icon does not bring user to home page

### ISSUE THREAD

**Issue by Elena273A0V** [topcoder-platform/Training-Challenges#61]
**Steps to Reproduce**:
1. Go to topcoder.com
2. Click on My Projects on top navigation menu
3. Click on Home icon in the top left corner

**Actual Result:**
User stays on My Project Page and no navigation menu is present to bring him back to topcoder.com home page

**Expected Result:** 
User should be brought to the home page topcoder.com

**Screencast URL:**
https://drive.google.com/open?id=17sEjo2t-hhorQIQa8PyFGyY9sr7bIrPu

**Device/OS/Browser Information:**
MacOS/Chrome 7

**Comment by nithyaasworld** [comment]
Good Job @Elena273A0V
