### ISSUE TITLE
[UI Isssue]-In COMPETITION RULES page 'Stage 2' date's year is not written Correctly

### ISSUE THREAD

**Issue by ritik02797** [topcoder-platform/Training-Challenges#63]
**Steps to Reproduce:**

1. Go To (https://www.topcoder.com/community/learn) this link.
2. Then Click on the  'Exlpore' menu tab at the top of page
3. Click on the 'TCO' option.
4. In the next page , Select the option 'GO TO TCO20 '  button 
5.After this, Select the "COMPETITION RULES" option at the top of  menu bar.
6.Scroll the page below And Check the date of Stage 2.

**Actual Result** :- Written date is "January 1, 20120"

**Expected Result** :-Date  Should be  "January 1, 2020"

**Device/OS/Browser Information:** Desktop/Windows 10/ Chrome

**Screenshot:**
![SS1](https://user-images.githubusercontent.com/59863088/72335515-18d14500-36e5-11ea-99cc-8215593ef00b.PNG)

**Comment by nithyaasworld** [comment]
Good Catch @ritik02797 

Just a note that, this is more of a Content Issue than a UI issue.
