### ISSUE TITLE
[UI Bug]-In JOBS page close icon is misalignment

### ISSUE THREAD

**Issue by seki2020** [topcoder-platform/Training-Challenges#64]
**Bug Title:** 
[UI Bug]-In JOBS page close icon is misaligned

**Steps to Reproduce:**
Go to [https://www.topcoder.com/company/jobs/](https://www.topcoder.com/company/jobs/)

**Actual Result:**
The close icon on the top right of the header was not aligned to the middle line.

**Expected Result:** 
It should be moved down several pixels to aligned to the middle line.

**Screenshots or screencast URL:**
![image](https://user-images.githubusercontent.com/46511237/72600087-ea09d780-394d-11ea-9918-47ba88d4f703.png)

**Device/OS/Browser Information:**
On PC and macOS from both Chrome and Safari

**Comment by nithyaasworld** [comment]
@seki2020 This may not really be a bug. May be, thats how it is designed.
