### ISSUE TITLE
[Functional bug] DevOps Engineer Job Link is 404

### ISSUE THREAD

**Issue by seki2020** [topcoder-platform/Training-Challenges#65]
**Bug Title:** 
[Functional bug] DevOps Engineer Job Link is 404

**Steps to Reproduce:**
Go to [https://www.topcoder.com/company/jobs/](https://www.topcoder.com/company/jobs/)
Click 'VIew Job Details' on the right of 'REMOTE DEVOPS ENGINEER'

**Actual Result:**
It is a dead link.

**Expected Result:** 
It should have content in [https://www.topcoder.com/company/jobs/remote-devops-engineer/](https://www.topcoder.com/company/jobs/remote-devops-engineer/) 

**Screenshots or screencast URL:**
![image](https://user-images.githubusercontent.com/46511237/72601354-3229f980-3950-11ea-9811-0bd2bb77ab17.png)

**Device/OS/Browser Information:**
All Platform on Desktop

**Comment by nithyaasworld** [comment]
Good Job @seki2020 

But this issue is fixed now. You can check the Job Details if you are interested on that :)
