### ISSUE TITLE
Mismatch between Business Phone and Country # UX BUG

### ISSUE THREAD

**Issue by leelaranik** [topcoder-platform/Training-Challenges#67]
**Bug Title:**

  Mismatch between Business Phone and Country in Profile Information

**Steps to Reproduce:**

1. Go to https://www.topcoder.com/
2. Click Login and enter user credentials
3. Click on 'My Projects' present at the top Left of the nav bar
4. Go to Profile Information Under My Profile which is at left side of the page.
5. Check the synchronization between Business Phone and Country in the Page opened.

**Actual:**

There is no proper synchronization between Business Phone and Country for some countries like Aland Islands,American Samoa,Anguilla,Antartica,Antigua and Barbuda, Australia,Bahamas,Barbados....etc

**Expected:**
The country field should properly fill on the submission of Business Phone Field. The Country name in both fields should be the same

**Device/OS/Browser Information:**

Windows 7 Chrome Latest

 **Screen Shot :**
![bug](https://user-images.githubusercontent.com/33871119/72617736-a6b86480-395f-11ea-9d34-b0e7f3cc016f.PNG)

**Comment by nithyaasworld** [comment]
@leelaranik Can you please provide more info on this bug?

Currently, upon changing the country, the corresponding country-code is filled into the Business Phone Text box automatically.
