### ISSUE TITLE
[Content]: copy right year information is not correct

### ISSUE THREAD

**Issue by EskindirA** [topcoder-platform/Training-Challenges#68]
Steps to Reproduce:
View left of the footer at topcoder.com 
Actual Result:
2019
Expected Result: 
2020
Screenshots or screencast URL:
![footer](https://user-images.githubusercontent.com/8351572/73247503-087b9880-41c2-11ea-8ed7-075294a9bc32.png)

Device/OS/Browser Information:
Windows 10, Google Chrome browser

**Comment by nithyaasworld** [comment]
@EskindirA Copyright info does not have to be the current year always. Checkout this interesting article: https://stackoverflow.com/a/2391555
