### ISSUE TITLE
[Functional]: Broken Links

### ISSUE THREAD

**Issue by EskindirA** [topcoder-platform/Training-Challenges#69]
Steps to Reproduce:
https://www.topcoder.com/members/
http://www.topcoder.com/tel:8558671356
Actual Result:
404
Expected Result: 
A page with content
Screenshots or screencast URL:
![link](https://user-images.githubusercontent.com/8351572/73348105-d9d0f100-4299-11ea-96f8-7f9c6f1e61bb.png)
![link](https://user-images.githubusercontent.com/8351572/73348290-32a08980-429a-11ea-910f-27e36b4377ad.png)
Device/OS/Browser Information:
Laptop/Windows 10/Google Chrome

**Comment by nithyaasworld** [comment]
@EskindirA Please provide more info about how did you get to the URL you have stated. Write the steps you have taken to reach to those pages from www.topcoder.com.
