### ISSUE TITLE
BOX-SIZING  Content of the topcoder 2020 pages

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/Training-Challenges#7]
1. Go to : https://tco20.topcoder.com/
**ACTUAL RESULT:**. The Topcoder page here: https://tco20.topcoder.com/  the page is not well sized and texts on the light are not viewable.
**EXPECTED RESULTS:** The page should feature in the same page and the texts should be seen in out flow page not cutting texts.

Device/OS/Browser Information: Linux,Ubuntu
OS: Kali
Browser information: Chromium Browser Version 73.0.3683.75 (Developer Build) built on Debian buster/side, running on Debian kali-rolling (32-bit)
[boxsize.zip](https://github.com/topcoder-platform/Training-Challenges/files/3898401/boxsize.zip)
     #####![boxsize](https://user-images.githubusercontent.com/37167721/69751875-07e26980-1161-11ea-8474-0453d395dd3e.jpg)

**Comment by nithyaasworld** [comment]
@Rokit12 

1. Appy the feedback given [here](https://github.com/topcoder-platform/Training-Challenges/issues/6#issuecomment-559368007) to this bug as well
2. Make the Title little more descriptive. Title for this bug could be "TCO20 Homepage: Text is out of user's view in <browername_here>"
3. What is the browser name? You have given the browser version number but am not sure what is the browser used here. Can you correct that one, please?

Again Congrats in finding this bug. You can very well participate in future Bug hunts. Each valid bug gets you $5 (upto a maximum of some limit) in real bug hunts. Just carefully follow the instructions given.
