### ISSUE TITLE
[Functional]: broken links

### ISSUE THREAD

**Issue by EskindirA** [topcoder-platform/Training-Challenges#70]
Steps to Reproduce:
https://www.topcoder.com/members/
http://www.topcoder.com/tel:8558671356
Actual Result:
404
Expected Result: 
A page with content
Screenshots or screencast URL:
![link](https://user-images.githubusercontent.com/8351572/73348105-d9d0f100-4299-11ea-96f8-7f9c6f1e61bb.png)
![link2](https://user-images.githubusercontent.com/8351572/73348494-9034d600-429a-11ea-9a15-0985def13498.png)
Device/OS/Browser Information:
Laptop/Windows 10/Google Chrome

**Comment by nithyaasworld** [comment]
Duplicate of https://github.com/topcoder-platform/Training-Challenges/issues/69
