### ISSUE TITLE
[UI] : Register button - challenge page

### ISSUE THREAD

**Issue by EskindirA** [topcoder-platform/Training-Challenges#71]
Steps to Reproduce:
Go into already registered challenge
Actual Result:
The register button is there active
Expected Result: 
disabled button or no button
Screenshots or screencast URL:
![register](https://user-images.githubusercontent.com/8351572/73531661-fc930f00-442b-11ea-8655-0f43bd1d9943.png)

Device/OS/Browser Information:
Laptop/Windows/Chrome

**Comment by nithyaasworld** [comment]
@EskindirA I cannot see the Register button active in your screenshot. Please provide more details (a Video or a very detailed step by step info of how to reproduce this issue).
