### ISSUE TITLE
Cannot go back to the previous page when navigated into "My projects" page.

### ISSUE THREAD

**Issue by varsha-chandran** [topcoder-platform/Training-Challenges#72]
[Steps to reproduce.docx](https://github.com/topcoder-platform/Training-Challenges/files/4179215/Steps.to.reproduce.docx)

**Comment by nithyaasworld** [comment]
@varsha-chandran Can you copy your Bug Details and paste instead of attaching the .docx file?

**Comment by nithyaasworld** [comment]
Please reach out to me for any help on this.
