### ISSUE TITLE
'Resources' page is not display after click  on 'Resource' link

### ISSUE THREAD

**Issue by SN143** [topcoder-platform/Training-Challenges#75]
Steps to Reproduce:

1.Navigate to the landing page / Home page https://www.topcoder.com/
2.Click on more button
3.Click on the Resources.

Actual Result:
Resource page is not get open , When user click on 'Resource' link.

Expected Results:
'Resource page' should be display when user click on 'Resources link'

Screencast
[Unclickable_Resource_Page_Link.docx](https://github.com/topcoder-platform/Training-Challenges/files/4208804/Unclickable_Resource_Page_Link.docx)
ome

Device/OS/Browser Information:
Laptop/Windows 10/Google Chr

**Comment by nithyaasworld** [comment]
@SN143 I am not able to reproduce this issue. Can you try again and let me know?

On a side note: Please paste the screenshot into the Bug description itself instead of attaching it via a .docx file
