### ISSUE TITLE
[UI Bug] video frame not fully accessed

### ISSUE THREAD

**Issue by shimaaahmedd** [topcoder-platform/Training-Challenges#76]
Bug Title: Introduction video hides its left buttons 
Steps to Reproduce:
1. open https://www.topcoder.com/
2. Click on play button at the left side of the page above the video.
3. Observe the right side of the full screen bubble.
Actual Result:
the setting button and a word on the top right hide behind the scroll bar
Expected Result: 
full screen video should appear with full access to its buttons
Screenshots or screencast URL:
https://1drv.ms/v/s!AklciaG7WEhHgQA94X2IY0FtX4MS
Device/OS/Browser Information:
<Laptop, windows 10 and Chrome>

**Comment by nithyaasworld** [comment]
Good Job @shimaaahmedd 

I am not able to reproduce the issue. May be, it is fixed already. But if you still see this issue, let me know. I will write to the support to get this fixed. Thanks!

**Comment by shimaaahmedd** [comment]
> Good Job @shimaaahmedd
> 
> I am not able to reproduce the issue. May be, it is fixed already. But if you still see this issue, let me know. I will write to the support to get this fixed. Thanks!

Same issue reproduces.
