### ISSUE TITLE
[UX / Usability Bug] Different Profile Picture 

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/Training-Challenges#77]
**Steps to Reproduce:**
Go to https://www.topcoder.com/ and then click **community** tab.

**Actual Result:**
Different profile picture show at the topcoder **home** page and **community** page.

**Expected Result:** 
Profile picture have to be same for all of topcoder pages.

**Screenshots or screencast URL:**
![](https://www.dropbox.com/s/mr0phs2dnc55xvb/diffProfilePicture.png?raw=1)

**Device/OS/Browser Information:**

- Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch

- OS: Windows 10 

- Browser: Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Good Job @Citra-citoru
