### ISSUE TITLE
[Accessibility Bug] when clicking on any of accessibility options

### ISSUE THREAD

**Issue by shimaaahmedd** [topcoder-platform/Training-Challenges#80]
Bug Title: Video starts when clicking on any of accessibility options
Steps to Reproduce:

open https://www.topcoder.com/company/community/
Click play button in the video then pause it
Click on accessibility button at the bottom right side of the page.
Click on Stop Animation.
Click on Play Animation.
Click on the video itself to pause it.
Click on any option in the Accessibility menu for example "Bigger Text".
Repeat pausing the video and choosing any option in the accessibility menu.
Actual Result:
The video plays when any accessibility option is clicked on.
Expected Result:
The video shouldn't play when clicked on any option other than play animation.
Screenshots or screencast URL:
https://onedrive.live.com/?authkey=%21AD3hfYhjQW1fgxI&cid=474858BBA1895C49&id=474858BBA1895C49%21129&parId=root&o=OneUp
Device/OS/Browser Information:
<Laptop, windows 10 and Chrome>

**Comment by nithyaasworld** [comment]
@shimaaahmedd The URL says the Video is no longer available. Can you please re-upload the video?

**Comment by shimaaahmedd** [comment]
> @shimaaahmedd The URL says the Video is no longer available. Can you please re-upload the video?
Sorry for that.
https://drive.google.com/file/d/1nZbjpq0zeB5UanjYxHVaUhJHm1lPGhJ0/view
