### ISSUE TITLE
[Functional]: Audio plays without displaying the video

### ISSUE THREAD

**Issue by shimaaahmedd** [topcoder-platform/Training-Challenges#81]
Bug Title: Audio plays without displaying the video when selecting play/stop animation in accessibility menu.
Steps to Reproduce:
open https://www.topcoder.com/
Click on accessibility button at the bottom right side of the page.
Click on Stop Animation.
Click on Play Animation.
Actual Result:
The audio plays without the video when accessibility option "Play Animation" is clicked on.
Expected Result:
The video should play when clicked on play animation with both video and audio.
Screenshots or screencast URL:
https://onedrive.live.com/?authkey=%21AD3hfYhjQW1fgxI&cid=474858BBA1895C49&id=474858BBA1895C49%21130&parId=root&o=OneUp
Device/OS/Browser Information:
<Laptop, windows 10 and Chrome>

**Comment by nithyaasworld** [comment]
Good Job @shimaaahmedd
