### ISSUE TITLE
[Usability bug] Navigation Panel is not present on My projects view

### ISSUE THREAD

**Issue by jyoti-c** [topcoder-platform/Training-Challenges#82]
**Steps to Reproduce - **

1.  Go to http://www.topcoder.com
2. Sign in with your account credentials 
3. Go to My projects 

**Expected Result** - Navigation Panel at the top of the page should be present
**Actual Result** - Navigation panel is not present and there is no way for the user to go back to the main page or any other sub page. 
![image](https://user-images.githubusercontent.com/29675947/76139289-6bd7d080-6074-11ea-80d5-2041a8611a8c.png)

Navigation panel not present at **My projects**
![image](https://user-images.githubusercontent.com/29675947/76139299-8742db80-6074-11ea-91d6-eb816c8aa18b.png)

Device/OS/Browser Information: Laptop/Windows 10/Chrome, Firefox, Edge

**Comment by nithyaasworld** [comment]
@jyoti-c Clicking on 'My Projects' redirects the user to another Topcoder's app called Connect and this behaviour is as designed. So this is not an issue.
