### ISSUE TITLE
[UI] Inconsistency in representation of field blog: When clicked on blog displayed under explore it navigates to blog on home screen

### ISSUE THREAD

**Issue by jyoti-c** [topcoder-platform/Training-Challenges#84]
**Steps to Reproduce**

1. Go to http://www.topcoder.com 
2. Go to Community
3. Click on Explore 
4. Click on Blog

**Expected** -  The user is taken to Blog page , and the parent navigation explore stays on the screen just like for other navigation - TCO or Programs

**Actual** - The user is taken to blog page of the home page and the parent navigation explore is not retained. 

Device/OS/Browser Information: Laptop/Windows 10/ Chrome 

[Topcoder - Community - Member Programs - Topcoder Open - Google Chrome 2020-03-07 21-03-55.zip](https://github.com/topcoder-platform/Training-Challenges/files/4302077/Topcoder.-.Community.-.Member.Programs.-.Topcoder.Open.-.Google.Chrome.2020-03-07.21-03-55.zip)

**Comment by nithyaasworld** [comment]
Nice reporting @jyoti-c

**Comment by jyoti-c** [comment]
> Nice reporting @jyoti-c

Thank you @nithyaasworld :)
