### ISSUE TITLE
[UI] Datasets Link is not Highlighted when viewing about Datasets under Tracks tab.

### ISSUE THREAD

**Issue by Nefeeza** [topcoder-platform/Training-Challenges#86]
Steps to Reproduce:
1, Go to URL http://www.topcoder.com 
2, Login Using Credentials.
3, Go to Community --> Tracks --> Competitive Programming --> Overview. Observe the link once 
    you clicked. It has underline and it looks bold.
4, Then Click on "Datasets" link near to Overview link. Observe the Datasets link.

Actual Result:
Datasets link is not Highlighted (Bold) and not has underline.

Expected Result: 
Datasets link should be highlighted (Bold) and it should have small underline when it is selected.

Screenshots or screencast URL:
![DatasetsLink_Highlight](https://user-images.githubusercontent.com/61901295/76150095-a6af2800-60b7-11ea-8ac1-2959bc855e49.png)

![HighlightReference](https://user-images.githubusercontent.com/61901295/76150100-b4fd4400-60b7-11ea-9341-e54a5592d256.png)

Device/OS/Browser Information:
Os: Windows 10
Version: Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Good job @Nefeeza
