### ISSUE TITLE
[UX Bug] Upper Arrow is Missing to reach the TOP of the page Quickly.

### ISSUE THREAD

**Issue by Nefeeza** [topcoder-platform/Training-Challenges#87]
Steps to Reproduce:
1, Go to URL http://www.topcoder.com 
2, Landing page displayed. Scroll down and observe.

Actual Result:
No Upper Arrow is available to reach the TOP of the page Quickly by User.

Expected Result: 
All page should have Upper arrow to reach the TOP of the page Quickly by User. 

Screenshots URL:
![UpperArrowMissing](https://user-images.githubusercontent.com/61901295/76159585-4f4e9d80-6133-11ea-93c6-6bd7a6391e88.png)

Device/OS/Browser Information:
Device: HP Laptop
OS: Windows 10
Browser: Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Nice Catch @Nefeeza
