### ISSUE TITLE
[Functional bug] Case Study page - Search Result is inadequate.

### ISSUE THREAD

**Issue by Nefeeza** [topcoder-platform/Training-Challenges#88]
Steps to Reproduce:
1, Go to URL http://www.topcoder.com
2, Go to "Case Studies" tab. Try to search "QA" Case study. Observe the result.

Actual Result:
Search result display only one Case Study "MICROSOFT".

Expected Result: 
Search result should display all Case studies regarding "QA". (QA - has 3 case studies)

Screenshots URL:
![CaseStudy_SearchItemMissing](https://user-images.githubusercontent.com/61901295/76159878-d69d1080-6135-11ea-884c-7db63879d24d.png)

![CaseStudy_SearchReference](https://user-images.githubusercontent.com/61901295/76159883-e3b9ff80-6135-11ea-82b0-4bc4d3e4d7dc.png)

Device/OS/Browser Information:
Device: HP Laptop
OS: Windows 10
Version: Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Good Catch! @Nefeeza
