### ISSUE TITLE
[Functional bug] Linking account to stackoverflow fails with "Application is diabled" errorpage

### ISSUE THREAD

**Issue by djoewie** [topcoder-platform/Training-Challenges#89]
**Steps to Reproduce:**
1. go to https://www.topcoder.com/settings/account#linked-accounts
2. click on icon of Stackoverflow
3. login in popup window of stackoverflow

**Actual Result:**
popup is saying "Application is disabled"

**Expected Result:** 
page to approve rights for using stackoverflow or popup closing and stackoverflow being added to the linked accounts

**Screenshots or screencast URL:**
![Capture](https://user-images.githubusercontent.com/5467805/78424146-b0528e00-766b-11ea-9a39-4b132acb459d.JPG)

**Device/OS/Browser Information:**
Windows 10 Home 1909 build 18363.720
chrome: Version 80.0.3987.149 (Official Build) (64-bit)
Firefox: 74.0.1 (32-bit)

**Comment by nithyaasworld** [comment]
Good Catch! @djoewie
