### ISSUE TITLE
[UX / Usability bug] covid-19 banner comes back

### ISSUE THREAD

**Issue by djoewie** [topcoder-platform/Training-Challenges#91]
closely related to #49, but no refresh or pagechange needed

**Steps to Reproduce:**
1.Go to https://www.topcoder.com/the-wonderland-of-the-5ws-and-how/
2. wait 2 seconds for the covid-19 banner to appear
3. close the banner as soon as it appears with the x that is found on the far right
4. wait around 1 minute

**Actual Result:**
popup of covid-19 comes back without option to let it close

**Expected Result:**
do not let it close at all OR keep it gone once it is closed

**Screenshots or screencast URL:**
![Capture](https://user-images.githubusercontent.com/5467805/78424963-581e8a80-7671-11ea-9f8b-3f6b2a4e92a3.JPG)

**Device/OS/Browser Information:**
Windows 10 Home 1909 build 18363.720
chrome: Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
@djoewie Nice Job in linking the related issue!!
