### ISSUE TITLE
[Content Bug] Spelling Mistakes in QA Thrive Article

### ISSUE THREAD

**Issue by detinsley1s** [topcoder-platform/Training-Challenges#92]
**Steps to Reproduce:**
1. Go to [https://www.topcoder.com/thrive/articles/QA & It's Future At Topcoder](https://www.topcoder.com/thrive/articles/QA%20&%20It's%20Future%20At%20Topcoder)

2. View the page.

**Actual Result:**
The word "its" is misspelled as "it's" and the word "interviews" is misspelled as "interview's."

**Expected Result:**
Each of the words should have been spelled correctly before publishing online.

**Screenshot:**
![topcoder screen](https://user-images.githubusercontent.com/10083390/78515182-76bc7880-777a-11ea-91c8-3e296b8f76ff.png)

**Device/OS/Browser:**
Latest version of Firefox on a Windows 10 PC

**Comment by nithyaasworld** [comment]
Perfect Classification of bug type!!
