### ISSUE TITLE
The system displays “404- HTTP” error when the user attempts to click on “My profile” option displayed on top right corner of the screen.

### ISSUE THREAD

**Issue by sharmi18** [topcoder-platform/Training-Challenges#93]
**Functional Bug:**
 Bug Title:
The system displays “404- HTTP” error when the user attempts to click on “My profile” option displayed on top right corner of the screen.

Steps to Reproduce:
•	Open the main screen of “https://www.topcoder.com/”.
•	Click on “MY Profile” option displayed on clicking logged in user details on the top corner of the screen.
•	The system displays “404 – HTTP error”

Expected Result: 
•	The system should display the profile information  of logged in user

Actual Result:
•	The system displays “404 – HTTP error”

Screenshots:
[Top coder - 404 error.docx](https://github.com/topcoder-platform/Training-Challenges/files/4466716/Top.coder.-.404.error.docx)

**Comment by nithyaasworld** [comment]
Good Catch @sharmi18 

But please paste the screenshot directly into your bug report instead of pasting it into .docx file and then attaching it.
