### ISSUE TITLE
Spacing to be corrected in the popup displayed on clicking Logged in user details on the right corner of the screen.

### ISSUE THREAD

**Issue by sharmi18** [topcoder-platform/Training-Challenges#94]
**UI Bug:**
1) Bug Title:
Spacing to be corrected in the popup displayed on clicking Logged in user details on the right corner of the screen.
Steps to Reproduce:
•	Open the main screen of “https://www.topcoder.com/”.
•	Click the logged in user’s mail ID displayed on the top right corner of the screen.
•	The system shall open a popup with the following information:
	My Profile
	Settings
	Help
	Logout
•	There is an extra space found below the “Logout” option.
Expected Result: 
The spacing needs to be the same both on the top and bottom of the popup.
Actual Result:
There is a single space left on the top of the popup but double space on the bottom of the popup.
Screenshots:
[Top coder UI Bug 1.docx](https://github.com/topcoder-platform/Training-Challenges/files/4466720/Top.coder.UI.Bug.1.docx)

**Comment by nithyaasworld** [comment]
Good Job @sharmi18
