### ISSUE TITLE
The accessibility menu doesn’t open with short key.

### ISSUE THREAD

**Issue by sharmi18** [topcoder-platform/Training-Challenges#96]
**Accessibility Issue**
The accessibility menu doesn’t open with short key.
Steps to Reproduce:
•	Open the main screen of “https://www.topcoder.com/”.
•	Click Ctrl+U
Expected Result: 
The system should open the “Accessibility Menu” displayed on the right corner of the screen when the respective short key is pressed.
Actual Result: 
The system doesn’t display the accessibility menu when the short key is pressed.

**Comment by nithyaasworld** [comment]
Good Job! @sharmi18  Just make sure to format your bugs with right spaces and indentation when necessary.
