### ISSUE TITLE
Ctrl + U doesn't open accessibility menu

### ISSUE THREAD

**Issue by emerzon1** [topcoder-platform/Training-Challenges#98]
Steps to Reproduce: 
1. Go to https://www.topcoder.com
2. Click on accessibility menu in bottom right
3. It says Click ctrl+u to open
4. Close it and press ctrl+u
5. It doesn't open.
Actual Result: Menu doesn't show
Expected Result: Menu pops up
Device: MacBook Air Catalina 2020, MacOSx

**Comment by nithyaasworld** [comment]
Please rewrite your bug by following the feedback given here: https://github.com/topcoder-platform/Training-Challenges/issues/97

**Comment by nithyaasworld** [comment]
This is duplicate of #96
