### ISSUE TITLE
Video disappears after viewing

### ISSUE THREAD

**Issue by emerzon1** [topcoder-platform/Training-Challenges#99]
Steps to Reproduce: 
1. Go to https://www.topcoder.com
2. Click on the video
3. Click escape
4. The video is gone
Actual Result: The video disappears
Expected Result: The video works and stays in its place
<img width="1440" alt="Screen Shot 2020-04-19 at 9 18 25 AM" src="https://user-images.githubusercontent.com/59055006/79688801-bbd2b700-821e-11ea-902c-c15390c63dff.png">

Device: MacBook Air Catalina 2020, MacOSx

**Comment by nithyaasworld** [comment]
Please rewrite your bug by following the feedback given here: #97
